baseurl = "https://15minutesoffame.be/"
title = "KooZic"
theme = ["universal-custo", "universal"]
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Download & Apps"
    url  = "/download"
    weight = 2

[[menu.main]]
    name = "Installation"
    url  = "/installation"
    weight = 3

[[menu.main]]
    name = "Screenshots"
    url  = "/screenshots"
    weight = 4

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq"
    weight = 5

[[menu.main]]
    name = "News"
    identifier = "news"
    url  = "/news"
    weight = 6

[params]
    viewMorePostLink = "/news/"
    author = "DocMarty84"
    defaultKeywords = ["streaming", "odoo", "python", "javascript"]
    defaultDescription = "Personal media server based on Odoo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "Not much to say ;-) Just file [an issue](https://github.com/docmarty84/koozic/issues) on GitHib for any request."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[Permalinks]
    news = "/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.features]
    enable = true

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Are you ready to rock?"
    subtitle = "Have a look at our demo server, or install your own!"
    link_url = "#"
    link_text = "Ooops!"
