baseurl = "https://15minutesoffame.be/nico/blog"
title = "15 Minutes of Fame"
author = "Marty"
canonifyurls = true
languageCode = "fr-fr"
paginate = 10

theme = ["my"]
disqusShortname = "15minutesoffame"

[taxonomies]
    tag = "tags"
    archive = "archives"

[params]
    defaultDescription = "Et si on se tournait vers les alternatives ?"
